baseURL = "https://www.bochkarev.io"
languageCode = "en-us"
theme = "desk"

title = "A.B."

[Author]
    name = "Alexey A. Bochkarev"
    email = "web@bochkarev.io"

# General parameters
[params]
    twitter = "a_bochka"
    github = "alex-bochkarev"
    keybase = "bochkarev"
    tg = "abochka"
    description = "Alexey Bochkarev: personal website"
    images = ["/home/AB.JPG"]

# Menu
[menu]
    # Main topline menu
    [[menu.main]]
      name = "Me"
      url = "/"
      weight = 1
    [[menu.main]]
      name = "Research"
      url = "/research/"
      weight = 2
    [[menu.main]]
      name = "Teaching"
      url = "/teaching/"
      weight = 3
    [[menu.main]]
      name = "Misc notes"
      url = "/notes/"
      weight = 4
    [[menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 5

    # Icons top-right-corner menu
    [[menu.side]]
      name="i-CV"
      url="/bochkarev_cv.pdf"
      weight=1
    [[menu.side]]
      name="i-envelope"
      url="mailto:a@bochkarev.io"
      weight=1
    [[menu.side]]
      name="i-key"
      url="/abochkarev-pubkey.asc"
      weight=1
    [[menu.side]]
      name="i-twitter"
      url="https://twitter.com/a_bochka"
      weight=3
    [[menu.side]]
      name="i-gh"
      url="https://github.com/alex-bochkarev"
      weight=4

[markup.goldmark.renderer]
    unsafe= true

